### ISSUE TITLE
put event numbers in stop document

### ISSUE THREAD

**Issue by CJ-Wright** [bluesky/databroker#188]
Port from https://github.com/NSLS-II/metadatastore/issues/263#issuecomment-269548123
>Would it be possible to stash the number of events (potentially on a per descriptor basis) in the run_stopdocument? This could be very convenient a) for just seeing how many events you have, b) be very helpful for broadcasting streams together.

Any suggestions on how to do this would be appreciated. Eg do I try to make MDS store the latest event seq_num and then put a dict of `{<data_key>: seq_num}`.

**Comment by danielballan** [comment]
You don't need to record a separate number of events per *data key*; you need to record it per *descriptor*. I would suggest adding a dictionary to the RunStop document mapping each descriptor uid to the number of events it encompasses (its max `seq_num`).

The information you need is tracked in the RunEngine's `_sequence_counters` attribute, which maps `(bundle_name, objs_read)` to an `itertools.count` object. Additionally, the `_descriptors` attribute maps these same keys -- `(bundle_name, objs_read)` -- to descriptor uid. By cross-referencing them, you can get the mapping you need.

Although this detail doesn't matter for your purposes, FYI, `bundle_name` is the same thing as `descriptor['name']` and `objs_read` is a `frozenset` of the ophyd objects (devices/signals) read for this descriptor. The `objs_read` is used internally by the RunEngine but, obviously, does not end up in the documents because devices can't be serialized. The devices' *names* do go into the documents, as `descriptor['object_keys']`.

**Comment by CJ-Wright** [comment]
Do you want this issue moved to bluesky?

**Comment by tacaswell** [comment]
Do we want to do per descriptor or per stream?

**Comment by danielballan** [comment]
> Do you want this issue moved to bluesky?

I don't mind track it here, since we have discussion going.

> Do we want to do per descriptor or per stream?

Per stream is probably what people would want most often. Per descriptor is more information (from which you can always compute per-stream). Maybe store per-descriptor and add a convenience method that computes per-stream?

**Comment by tacaswell** [comment]
@danielballan Sold on descriptors vs stream

What will we do when the archiver or tag/notes/comments event sources are used?  They will produce descriptors and streams that we do not know about at Stop creating time.

 - no entry and consumers just need to be wary
 - add an entry (as at retrieval time we know everything) with a sentinal for 'don't know'
 - add entry and count at retrieval time

**Comment by danielballan** [comment]
I think 'no entry' is clearest. Consumers either need to be wary of 'no entry' or they need to be aware of our "don't know" sentinel. The former is more universal.

Adding a count at retrieval time could potentially mean loading all the data, depending on the data source, so I think we do not want to guarantee that we will always do that. But in cases where we can cheaply add a count at retrieval time, we could.

**Comment by danielballan** [comment]
@CJ-Wright As a heads up -- I'm not sure if this was still on your back burner, but we received more user requests for this feature, so I took care of it myself in https://github.com/NSLS-II/bluesky/pull/852

**Comment by CJ-Wright** [comment]
@danielballan Thanks for the heads up. My back burner is the size of the Yellowstone caldera at this point so I would not anticipate anything put there getting developed in the near future.
