### ISSUE TITLE
Rethink Header.events and Header.stream

### ISSUE THREAD

**Issue by danielballan** [bluesky/databroker#207]
Believe or not, @tacaswell is advocating for a name change. I'm just the note-taker here. Adjust my reputation among my peers accordingly.

* Header.events -> Header.stream
* Header.stream -> Header.documents

Also, the new Header.stream should *require* its stream_name arg and disallow `ALL`. That is, it should return rows from a table. That analogy implies that the rows have homogeneous columns.

**Comment by danielballan** [comment]
@tacaswell Thinking on this, I like `Header.documents()` (or maybe `Header.docs()`) but I think `Header.events()` is more clear than `Header.stream()`. It only returns Event documents.

**Comment by tacaswell** [comment]
I seem to have flipped a few times on this as I was arguing against this at lunch yesterday.

I think `Header.events` -> just event dicts with no names and no other types, but all from a single stream (and it is the users job to have previously gotten the descriptors (if they care).

`H.docs()` seems like it should give us documentation (see 'readthedocs') so `documents` is probably better if longer.

In any case, we should drop 'stream' as a method because it is a verb ('to stream the documents out'), a general noun ('a stream of documents'), and an in house term-of-art ("a run has N streams").

**Comment by danielballan** [comment]
I'll quickly write a PR for this while we are in agreement! :-)

**Comment by CJ-Wright** [comment]
Will there be a header based method for getting all the data associated with a `run_start` out?

**Comment by danielballan** [comment]
Yep, that's `h.documents()`. You can narrow it by stream with `h.documents('primary')` etc. but the default for that method is to give you everything.
