### ISSUE TITLE
Getting events from header is awkward (db[uid]['events']() )

### ISSUE THREAD

**Issue by jrmlhermitte** [bluesky/databroker#307]
The following:
```python
hdr = db[-1]
evts = hdr['events']
# get the generator for the event:
evts = evts()
next(evts)# etc...
```

I feel that may be a mistake? Should it not be (minus the `evts = evts()` step):
```python
hdr = db[-1]
evts = hdr['events']
next(evts)# etc...
```
Thanks!
I am using `0.9.3+0.gcae5bb2.dirty`

**Comment by danielballan** [comment]
The intended usage is `hdr.events()`. See [Header API documentation](https://nsls-ii.github.io/databroker/api.html#the-header-object) and [`header.event()`](https://nsls-ii.github.io/databroker/_as_gen/databroker.Header.events.html#databroker.Header.events) in particular.

Header uses the `attr.s` library which to my taste is a little bit more magic than we need for `Header`. @tacaswell, do you want to make the case here for why we are using `attr.s`? The behavior that @ordirules tripped over seems legitimately confusing to me. Could be be using `attr.s` better to avoid it?

[I answered in Slack before I noticed the issue. Sorry for the noise!]

**Comment by tacaswell** [comment]
This isn't `attr.s` fault, but mine.  By default `attr.s` does not pretend to be a dictionary for back compatibility, but `Header` does.  Instead of only allowing `{'start', 'stop', 'descriptors'}` through `__getitem__` it is just getting bounced straight to `__getattr__`.  `hdr['events']` should have raised a `KeyError`.

I have a fix for this on my desktop at work I'll push when I get in.

**Comment by jrmlhermitte** [comment]
as of now `hdr['events']` still doesn't raise `KeyError`.
version : 0.9.3+16.g3841b60.dirty

if pushed we can close this issue.

**Comment by tacaswell** [comment]
I must have never pushed that branch...
