### ISSUE TITLE
database connection with uri and intake compatibility

### ISSUE THREAD

**Issue by gwbischof** [bluesky/databroker#404]
To connect to a mongo cluster with load balancing, we need to specify more information in the connection string than allowed by databroker currently.  

A connection string uri for a cluster looks something like this:
mongodb://user:password@mongo01:27212,mongo02:27213,mongo03:27214/database?authSource=admin

I think we should be able to connect to a datasource by uri, so we can specify any additional information that we need. 

Intake allows us to do this, when we merge: https://github.com/NSLS-II/databroker/pull/392 we will need to figure out how to handle intake and databroker config files.

**Comment by dylanmcreynolds** [comment]
I think issue has been fixed...I certainly use full mongo urls in my configuration. But this is an imperfect solution. I don't know if I should submit a new issue or track here.

Storing username and password in the yml file is not very secure. In fact, I have found in playing with intake-server, that the server displays the full yaml file when one GETs to http://intake-server-host/vi/info. So, by default, if nothing is done, anyone can see the full mongo connection string. Not good.

What if we were to enhance BlueskyMongoCatalog so that both metadatastore_db and asset_registry_db were optional, and if not passed in (through the yaml file), then and environment variable is checked for each? That would play nicely with intake-server as well as containers.

**Comment by danielballan** [comment]
Intake supports templated variables in the YAML files. I think this may be all we need here. https://intake.readthedocs.io/en/latest/catalog.html?highlight=env#templating

**Comment by danielballan** [comment]
Example of where we have used this in a Mongo URI: https://github.com/NSLS-II/scipy-binder/blob/master/binder/catalog.yml

**Comment by dylanmcreynolds** [comment]
That totally works for me. Many thanks.
