### ISSUE TITLE
hdr.table() returns an empty dataframe for v1

### ISSUE THREAD

**Issue by mrakitin** [bluesky/databroker#516]
Observed yesterday at CSX.

Databroker 1.0.0b6:
![20200128_182046](https://user-images.githubusercontent.com/13209176/73358386-809e9880-426c-11ea-8447-d3b71291e6a6.jpg)

Databroker 0.13.0:
![20200128_182152](https://user-images.githubusercontent.com/13209176/73358431-9318d200-426c-11ea-9270-8a043004e44b.jpg)

**Comment by gwbischof** [comment]
I am working on debugging this. When I use databroker 1.0 the run only shows 12 documents. When I use databroker 0.13 it shows 889 documents.

**Comment by gwbischof** [comment]
Also with databroker v1.0.0b3 there are 543 documents for this run

**Comment by gwbischof** [comment]
I checked a different scan and the number of documents for the different versions of databroker matched.

**Comment by gwbischof** [comment]
@mrakitin suggested that we add tests to make sure we get the same data for v0,v1,v2 brokers.

**Comment by gwbischof** [comment]
I think the problem is that each time read_partition is called. self._partitions is None, and the partitions are reloaded each time. When filling there is a UnresolvableForeignKeyError, this inserts a new partitions into self._partitions. But the next call to read_partition self._partitions is None again and the partition that was inserted due to the UnresolvableForeignKeyError is missing.

**Comment by gwbischof** [comment]
This is the problem, I removed the line of code that inserts the missing datum into BlueskyEventStream._partitions, and I got the correct number of events. What is happening is that when we read partition 0, we call load_partitions because self._partitions is None, and then return partition 0. Then we read_partition 1, self._partitions in None again, so we call load_partitions. We try to return partition 1, but we find that there are missing datum, so we insert the missing datum into self._partitions at index 1. This shifts the old partition 1 to partition 2. Then we return the new partition 1. Then we try to get the next partition (partition 2). self._partitions is None again, so we call load_partitions which gives us partition 0 and partition 1.  When we try to return partition 2, we find that there is no partition 2, so we return an empty list. If self._partitions kept its value this would work correctly.
