### ISSUE TITLE
Allow the config file to have a uri instead of host-port

### ISSUE THREAD

**Issue by gwbischof** [bluesky/databroker#537]
Host port doesn't allow us to configure the authentication or load balancing that is required for connection to the central mongo cluster. Currently databroker only support host-port.

https://api.mongodb.com/python/current/examples/authentication.html#authentication-examples

**Comment by danielballan** [comment]
To elaborate, the [old-style configuration files](https://blueskyproject.io/databroker/v1/configuration.html#v0-configuration) have the limitation @gwbischof described above. The [new-style configuration files](https://blueskyproject.io/databroker/v2/administrator/index.html#mongodb-example) support a generic URI and are fully compatible with MongoDB's [default authentication mechanism](https://api.mongodb.com/python/current/examples/authentication.html#scram-sha-256-rfc-7677).

This issue should not affect facilities that are starting from v1/v2. We at NSLS care about it because we still want the option of falling back to v0 for at least one operating cycle.
