### ISSUE TITLE
Upserting an xarray wipes out its .indexes, but not its .coords; leads to unexpected behavior when slicing

### ISSUE THREAD

**Issue by ronpandolfi** [bluesky/databroker#594]
When upserting composed events containing xarray data with coords set, the coords propagate through to the catalog and `.to_dask()`, however the `.indexes` gets wiped out and replaced with the 'time' indices. This leads to weird behavior when trying to slice. The `.coords` is still populated, so I expected to be able to slice with `.sel(**slc, method='nearest')`, but this fails with:
```
ValueError: cannot supply ``method`` or ``tolerance`` when the indexed dimension does not have an associated coordinate.
```

**Comment by danielballan** [comment]
Would it difficult to share an SSCCE?

**Comment by ronpandolfi** [comment]
Will share one soon. Also, it should be interesting that I can restore the indexes (supplementing the time indexes) with:
```
data.reindex({dim:data.coords[dim] for dim in data.dims})
```

**Comment by ronpandolfi** [comment]
How does this look?
```python
@pytest.fixture
def xarray_catalog():
    import time
    import event_model
    def catalog_generator():
        data = np.ones((10,10,10))

        energy = np.arange(data.shape[2])
        sample_x = np.arange(data.shape[1])
        sample_y = np.arange(data.shape[0])

        xarray = DataArray(data, dims=['y (μm)', 'x (μm)', 'E (eV)'], coords=[sample_y, sample_x, energy])

        # Compose run start
        run_bundle = event_model.compose_run()  # type: event_model.ComposeRunBundle
        start_doc = run_bundle.start_doc
        yield 'start', start_doc

        # Compose descriptor
        source = 'nxSTXM'
        frame_data_keys = {'raw': {'source': source,
                                   'dtype': 'number',
                                   'dims': xarray.dims,
                                   # 'coords': [energy, sample_y, sample_x],
                                   'shape': data.shape}}
        frame_stream_name = 'primary'
        frame_stream_bundle = run_bundle.compose_descriptor(data_keys=frame_data_keys,
                                                            name=frame_stream_name,
                                                            # configuration=_metadata(path)
                                                            )
        yield 'descriptor', frame_stream_bundle.descriptor_doc

        yield 'event', frame_stream_bundle.compose_event(data={'raw': xarray},
                                                         timestamps={'raw': time.time()})

        yield 'stop', run_bundle.compose_stop()

    return catalog_generator


def test_xarray_mixed_state(xarray_catalog):
    from databroker.in_memory import BlueskyInMemoryCatalog
    docs = list(xarray_catalog())
    uid = docs[0][1]["uid"]
    catalog = BlueskyInMemoryCatalog()
    catalog.upsert(docs[0][1], docs[-1][1], xarray_catalog, [], {})

    data = catalog[uid].primary.to_dask()['raw']

    # FIXME: Unexpected failure, since data.indexes has been wiped out by databroker
    with pytest.raises(Exception) as exc:
        assert data.sel({'E (eV)': 0}, method='nearest') is not None

    assert list(data.indexes.keys()) == ['time']

    # NOTE: However, we can put data.indexes back together, since databroker doesn't touch data.coords
    data = data.reindex({dim: data.coords[dim] for dim in data.dims})

    assert list(data.indexes.keys()) == ['time', 'y (μm)', 'x (μm)', 'E (eV)']

    assert data.sel({'E (eV)': 0}, method='nearest') is not None
```

**Comment by danielballan** [comment]
Oh, the problem is that this code tries to put an `xarray.DataArray` into an Event document. That is not supported. The reason that it even _partly_ works in this example (`data.coords` survives) is that this is all in memory. In general, the contents of `event["data"]` need to be unstructured and made of built-in types* so that MongoDB, JSON, or msgpack can serialize it.

*We extend the serializers to also support `numpy.ndarray` either via a native extension mechanism (msgpack) or by converting to (nested) lists (JSON, MongoDB). The validation code in `compose_event` is (I think) letting the `xarray.Dataset` pass as "numpy-like" ~but that is accidental~. That can be good in the sense that it doesn't force you to explicitly convert to `numpy.ndarray`, but it can be bad if you have the expectation that the `Dataset`'s additional, richer semantics will be retained.

It is reasonable to wonder, "Why can't I put structued data in `event["data"]`? Should we allow that?" Per the docs at https://blueskyproject.io/event-model/data-model.html#event-document:

> It is intentional that the values in the “data” and “timestamps” dictionaries do not have structure. The values may be numeric, bool, null (None), or a homogeneous N-dimensional array of any of these. The values are never objects or dictionaries (to use the JSON and Python terminology respectively). This requirement allows document-consumers to make useful simplifying assumptions. As another justification for this design, consider that if we allowed one level of nesting in “data”, then it could lead to wanting those values to allow nesting and so on, which would lead us to accepting arbitrarily nested structured data. This in turn would makes the Event Descriptors significantly more complex. Thus, we require that the values in “data” never be structured.

My best recommendation is to put the `coords` and `indexes` into their own columns in the Event, so that the consumer can access / reassemble.

**Comment by ronpandolfi** [comment]
Hm, your rationale makes sense, but I'm again disappointed by the indirectness required to get coords, a primary feature of xarray, back out of databroker, in contrast to dims, which works nicely on its own.

Closing, but still hoping for better support for this feature.
