### ISSUE TITLE
Brokers loaded from configuration files in DB search dirs have no .metadata["catalog_dir"]

### ISSUE THREAD

**Issue by ronpandolfi** [bluesky/databroker#606]
Brokers loaded via intake's mechanisms get a useful "catalog_dir" metadata field injected. When using databroker's load mechanisms, this is absent. 

Thanks @ihumphrey

**Comment by danielballan** [comment]
[This was discussed on a call but I'll summarize here in case someone else hits this issue.]

Old-style configuration files don't have a `catalog_dir` because there is no catalog _file_ at all. We generate a Catalog based on databroker's old deprecated config file system.

Solution is to move to the new intake-style config files.
